server:
  applicationConnectors:
  - type: http
    port: 9080
  adminConnectors:
  - type: http
    port: 9081

logging:
  level: INFO
  loggers:
    "net.lisanza":
      level: DEBUG
      additive: false
      appenders:
      - type: file
        currentLogFilename: logs/dropunit-simulator.log
        archivedLogFilenamePattern: logs/dropunit-simulator-%d.log.gz
        archivedFileCount: 5
        timeZone: UTC
      - type: console
        target: stderr
    â€œnet.lisanza.dropunit.simulator.logging":
      level: DEBUG

endpoints:
  - path: "/default/path/one"
    method: "GET"
    responseCode: 200
    responseContentType: "application/xml"
    responseBodyFileName: "src/main/resources/endpoints/response-body-one.xml"
  - path: "/default/path/one?parameter=value"
    method: "GET"
    responseCode: 200
    responseContentType: "application/xml"
    responseBodyFileName: "src/main/resources/endpoints/response-body-one.xml"
  - path: "/default/path/two"
    method: "GET"
    responseCode: 200
    responseContentType: "application/xml"
    responseBodyFileName: "src/main/resources/endpoints/response-body-two.xml"
  - path: "/default/path/three"
    method: "GET"
    responseCode: 200
    responseContentType: "application/json"
    responseBodyFileName: "src/main/resources/endpoints/response-body-three.json"
  - path: "/default/path/four"
    method: "GET"
    responseCode: 404
    responseContentType: "application/json"
    responseBodyFileName: ""
  - path: "/default/path/five"
    method: "POST"
    request:
      contentType: "application/xml"
      patterns:
        - "<abc>"
        - "</abc>"
    responseCode: 200
    responseContentType: "application/xml"
    responseBodyFileName: "src/main/resources/endpoints/response-body-one.xml"
  - path: "/default/path/five"
    method: "POST"
    request:
      contentType: "application/xml"
      patterns:
        - "<xyz>"
        - "</xyz>"
    responseCode: 200
    responseContentType: "application/xml"
    responseBodyFileName: "src/main/resources/endpoints/response-body-two.xml"
  - path: "/default/path/six"
    method: "GET"
    delay: 20000 # ms
    responseCode: 200
    responseContentType: "application/xml"
    responseBodyFileName: "src/main/resources/endpoints/response-body-one.xml"